### ISSUE TITLE
Passing data to landing for amma

### ISSUE THREAD

**Issue by nyacide** [nyacide/amma#40]
[AMMA texte landing.docx](https://github.com/nyacide/amma/files/451630/AMMA.texte.landing.docx)

**Comment by nyacide** [comment]
Plasați acest text la rubrica Mai mulți cumpărători și puneți în cuvîntul „cumpărători” toate căciulițele deasupra literei „a”.

Mai mulți cumpărători

Vînzările se realizează prin intermediul ofertelor speciale, care presupun un preț mai redus decît cel de pe piață și care se bazează pe fenomenul cumpărăturilor în grup. Datorită unui număr mare de cumpărători interesați de propunere, produsele cu amănuntul se pot cumpăra la prețuri angro.

**Comment by nyacide** [comment]
additional tasks from #43 
1.De luat punctul din titlu(sub logo).
2."Crează " de schimbat cu "Creează" --> La etapele de lucru
3.Mai mulți cumpărători -->căciulița literei "a" -cumpărători
4.Etapele de lucru "ALE" în loc de "A" magazinului

**Comment by WebStra** [comment]
All changes completed!
